/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoGalleryRouteImport } from './routes/video-gallery'
import { Route as TeamSingleRouteImport } from './routes/team-single'
import { Route as TeamRouteImport } from './routes/team'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImageGalleryRouteImport } from './routes/image-gallery'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as DonationRouteImport } from './routes/donation'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogVieNewHopeRouteImport } from './routes/blog-vie-new-hope'
import { Route as BlogOrientationProfessionnelleRouteImport } from './routes/blog-orientation-professionnelle'
import { Route as BlogDeveloppementCompetencesRouteImport } from './routes/blog-developpement-competences'
import { Route as BlogCollecteDeFondsRouteImport } from './routes/blog-collecte-de-fonds'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWebhooksSebpayRouteImport } from './routes/api/public/webhooks/sebpay'

const VideoGalleryRoute = VideoGalleryRouteImport.update({
  id: '/video-gallery',
  path: '/video-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSingleRoute = TeamSingleRouteImport.update({
  id: '/team-single',
  path: '/team-single',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageGalleryRoute = ImageGalleryRouteImport.update({
  id: '/image-gallery',
  path: '/image-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationRoute = DonationRouteImport.update({
  id: '/donation',
  path: '/donation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogVieNewHopeRoute = BlogVieNewHopeRouteImport.update({
  id: '/blog-vie-new-hope',
  path: '/blog-vie-new-hope',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogOrientationProfessionnelleRoute =
  BlogOrientationProfessionnelleRouteImport.update({
    id: '/blog-orientation-professionnelle',
    path: '/blog-orientation-professionnelle',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogDeveloppementCompetencesRoute =
  BlogDeveloppementCompetencesRouteImport.update({
    id: '/blog-developpement-competences',
    path: '/blog-developpement-competences',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCollecteDeFondsRoute = BlogCollecteDeFondsRouteImport.update({
  id: '/blog-collecte-de-fonds',
  path: '/blog-collecte-de-fonds',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksSebpayRoute = ApiPublicWebhooksSebpayRouteImport.update({
  id: '/api/public/webhooks/sebpay',
  path: '/api/public/webhooks/sebpay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/blog-collecte-de-fonds': typeof BlogCollecteDeFondsRoute
  '/blog-developpement-competences': typeof BlogDeveloppementCompetencesRoute
  '/blog-orientation-professionnelle': typeof BlogOrientationProfessionnelleRoute
  '/blog-vie-new-hope': typeof BlogVieNewHopeRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donation': typeof DonationRoute
  '/faqs': typeof FaqsRoute
  '/image-gallery': typeof ImageGalleryRoute
  '/login': typeof LoginRoute
  '/team': typeof TeamRoute
  '/team-single': typeof TeamSingleRoute
  '/video-gallery': typeof VideoGalleryRoute
  '/api/public/webhooks/sebpay': typeof ApiPublicWebhooksSebpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/blog-collecte-de-fonds': typeof BlogCollecteDeFondsRoute
  '/blog-developpement-competences': typeof BlogDeveloppementCompetencesRoute
  '/blog-orientation-professionnelle': typeof BlogOrientationProfessionnelleRoute
  '/blog-vie-new-hope': typeof BlogVieNewHopeRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donation': typeof DonationRoute
  '/faqs': typeof FaqsRoute
  '/image-gallery': typeof ImageGalleryRoute
  '/login': typeof LoginRoute
  '/team': typeof TeamRoute
  '/team-single': typeof TeamSingleRoute
  '/video-gallery': typeof VideoGalleryRoute
  '/api/public/webhooks/sebpay': typeof ApiPublicWebhooksSebpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/blog-collecte-de-fonds': typeof BlogCollecteDeFondsRoute
  '/blog-developpement-competences': typeof BlogDeveloppementCompetencesRoute
  '/blog-orientation-professionnelle': typeof BlogOrientationProfessionnelleRoute
  '/blog-vie-new-hope': typeof BlogVieNewHopeRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/donation': typeof DonationRoute
  '/faqs': typeof FaqsRoute
  '/image-gallery': typeof ImageGalleryRoute
  '/login': typeof LoginRoute
  '/team': typeof TeamRoute
  '/team-single': typeof TeamSingleRoute
  '/video-gallery': typeof VideoGalleryRoute
  '/api/public/webhooks/sebpay': typeof ApiPublicWebhooksSebpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/admin'
    | '/blog-collecte-de-fonds'
    | '/blog-developpement-competences'
    | '/blog-orientation-professionnelle'
    | '/blog-vie-new-hope'
    | '/contact'
    | '/dashboard'
    | '/donation'
    | '/faqs'
    | '/image-gallery'
    | '/login'
    | '/team'
    | '/team-single'
    | '/video-gallery'
    | '/api/public/webhooks/sebpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/admin'
    | '/blog-collecte-de-fonds'
    | '/blog-developpement-competences'
    | '/blog-orientation-professionnelle'
    | '/blog-vie-new-hope'
    | '/contact'
    | '/dashboard'
    | '/donation'
    | '/faqs'
    | '/image-gallery'
    | '/login'
    | '/team'
    | '/team-single'
    | '/video-gallery'
    | '/api/public/webhooks/sebpay'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/admin'
    | '/blog-collecte-de-fonds'
    | '/blog-developpement-competences'
    | '/blog-orientation-professionnelle'
    | '/blog-vie-new-hope'
    | '/contact'
    | '/dashboard'
    | '/donation'
    | '/faqs'
    | '/image-gallery'
    | '/login'
    | '/team'
    | '/team-single'
    | '/video-gallery'
    | '/api/public/webhooks/sebpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AdminRoute: typeof AdminRoute
  BlogCollecteDeFondsRoute: typeof BlogCollecteDeFondsRoute
  BlogDeveloppementCompetencesRoute: typeof BlogDeveloppementCompetencesRoute
  BlogOrientationProfessionnelleRoute: typeof BlogOrientationProfessionnelleRoute
  BlogVieNewHopeRoute: typeof BlogVieNewHopeRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DonationRoute: typeof DonationRoute
  FaqsRoute: typeof FaqsRoute
  ImageGalleryRoute: typeof ImageGalleryRoute
  LoginRoute: typeof LoginRoute
  TeamRoute: typeof TeamRoute
  TeamSingleRoute: typeof TeamSingleRoute
  VideoGalleryRoute: typeof VideoGalleryRoute
  ApiPublicWebhooksSebpayRoute: typeof ApiPublicWebhooksSebpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-gallery': {
      id: '/video-gallery'
      path: '/video-gallery'
      fullPath: '/video-gallery'
      preLoaderRoute: typeof VideoGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-single': {
      id: '/team-single'
      path: '/team-single'
      fullPath: '/team-single'
      preLoaderRoute: typeof TeamSingleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-gallery': {
      id: '/image-gallery'
      path: '/image-gallery'
      fullPath: '/image-gallery'
      preLoaderRoute: typeof ImageGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donation': {
      id: '/donation'
      path: '/donation'
      fullPath: '/donation'
      preLoaderRoute: typeof DonationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog-vie-new-hope': {
      id: '/blog-vie-new-hope'
      path: '/blog-vie-new-hope'
      fullPath: '/blog-vie-new-hope'
      preLoaderRoute: typeof BlogVieNewHopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog-orientation-professionnelle': {
      id: '/blog-orientation-professionnelle'
      path: '/blog-orientation-professionnelle'
      fullPath: '/blog-orientation-professionnelle'
      preLoaderRoute: typeof BlogOrientationProfessionnelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog-developpement-competences': {
      id: '/blog-developpement-competences'
      path: '/blog-developpement-competences'
      fullPath: '/blog-developpement-competences'
      preLoaderRoute: typeof BlogDeveloppementCompetencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog-collecte-de-fonds': {
      id: '/blog-collecte-de-fonds'
      path: '/blog-collecte-de-fonds'
      fullPath: '/blog-collecte-de-fonds'
      preLoaderRoute: typeof BlogCollecteDeFondsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/sebpay': {
      id: '/api/public/webhooks/sebpay'
      path: '/api/public/webhooks/sebpay'
      fullPath: '/api/public/webhooks/sebpay'
      preLoaderRoute: typeof ApiPublicWebhooksSebpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AdminRoute: AdminRoute,
  BlogCollecteDeFondsRoute: BlogCollecteDeFondsRoute,
  BlogDeveloppementCompetencesRoute: BlogDeveloppementCompetencesRoute,
  BlogOrientationProfessionnelleRoute: BlogOrientationProfessionnelleRoute,
  BlogVieNewHopeRoute: BlogVieNewHopeRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DonationRoute: DonationRoute,
  FaqsRoute: FaqsRoute,
  ImageGalleryRoute: ImageGalleryRoute,
  LoginRoute: LoginRoute,
  TeamRoute: TeamRoute,
  TeamSingleRoute: TeamSingleRoute,
  VideoGalleryRoute: VideoGalleryRoute,
  ApiPublicWebhooksSebpayRoute: ApiPublicWebhooksSebpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
